language: node_js
node_js:
    - stable
cache:
    directories:
        - node_modules
script:
    - npm run lint
    - npm run test
    - npm run build
    - npm run export
    - touch out/.nojekyll # disable jekyll on gh pages
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: out
    on:
        branch: main
