language: node_js
node_js:
    - stable
cache:
    directories:
        - node_modules
jobs:
    inclue:
        - stage: lint
          script:
              - npm run lint
        - stage: test
          script:
              - npm run test
        - stage: deploy
          if: branch = master
          script:
              - npm run build
              - npm run export
              - touch out/.nojekyll
          deploy:
              provider: pages
              skip_cleanup: true
              github_token: $github_token
              local_dir: out
              on:
                  branch: main
